---
title: "Análisis de Series Temporales de Lluvia: Estación VENADO ORO VIVERO [21205580]"
author: "[Dónoban Rojas](https://www.linkedin.com/in/donoban-rojas/)"
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    highlight: "breezedark"
    css: style.css
    code_folding: hide
    config:
      toc:
        before: |
          <li><a href="./">Series Temporales de Lluvia</a></li>
      download: ["pdf", "epub"]
      fontsettings:
        theme: night
        family: sans
        size: 2
    output_dir: "docs"
    includes:
      in_header: preamble.html
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: seriestiempo
description: "Análisis de datos de precipitación diaria de la estación VENADO ORO VIVERO en Bogotá"
---

# Importancia del Análisis de la Precipitación

Se propone el análisis de los datos de precipitación diaria registrados en la estación climatológica “VENADO ORO VIVERO”, ubicada en Bogotá, con coordenadas 4.60° de latitud y -74.06° de longitud, y una altitud de 2,725 metros sobre el nivel del mar. Esta estación, parte de la red del Instituto de Hidrología, Meteorología y Estudios Ambientales (IDEAM), cuenta con datos históricos desde el 1 de agosto de 1965 hasta el 10 de agosto de 2022. La variable seleccionada es la precipitación diaria (PTPM_CON), medida en milímetros (mm).

**Justificación del uso de datos de precipitación**

El análisis de las series temporales de precipitación es fundamental para comprender las características climáticas locales y su evolución a lo largo del tiempo. Este tipo de estudio permite identificar patrones estacionales, tendencias a largo plazo y fenómenos extremos, aspectos cruciales para pronosticar eventos climáticos relevantes. La estación VENADO ORO VIVERO ha sido seleccionada por su accesibilidad de datos y su cercanía a la Pontificia Universidad Javeriana sede Bogotá, donde actualmente se lleva a cabo una investigación aplicada sobre Sistemas Urbanos de Drenaje Sostenible (SuDS) en el contexto del cambio climático. Los datos locales de precipitación son esenciales para la predicción de escenarios climáticos futuros, lo que facilitará la adaptación y optimización de los SuDS ante las variaciones climáticas proyectadas.

A pesar de que la serie temporal de la estación VENADO ORO VIVERO abarca más de cinco décadas, es relevante señalar que presenta algunas lagunas en los registros. Sin embargo, esta serie proporciona una base valiosa para el análisis de tendencias, estacionalidad, autocorrelación y el desarrollo de modelos predictivos. El valor añadido de este análisis radica en la aplicación de técnicas avanzadas de series temporales, que permitirán no solo detectar patrones climáticos recurrentes, sino también identificar anomalías y cambios estructurales en las precipitaciones.

El enfoque de este estudio se centra en el desarrollo de competencias técnicas y en el manejo de herramientas estadísticas aplicables a diversos contextos de análisis climático. Aunque los datos pueden ser útiles para futuras investigaciones, como el modelado hidrológico o el análisis del cambio climático, su proximidad a la Pontificia Universidad Javeriana los convierte en especialmente relevantes en el marco de la investigación en curso sobre SuDS.

**Fuentes y permisos**

Los datos utilizados provienen del Instituto de Hidrología, Meteorología y Estudios Ambientales (IDEAM), específicamente a través de la plataforma pública DHIME (http://dhime.ideam.gov.co/atencionciudadano/). DHIME es un sistema de acceso público que permite la consulta y descarga de datos meteorológicos e hidrológicos. Estos datos están disponibles sin restricciones para fines académicos e investigativos, cumpliendo con las políticas de uso del IDEAM.

Adicionalmente, los datos obtenidos a través de la plataforma del IDEAM están disponibles para su verificación y consulta en el repositorio oficial, accesible en el siguiente enlace: [Descargar datos](https://raw.githubusercontent.com/dosrojasce/RainTimeSeries/refs/heads/main/21205580-PTPM_CON.csv)
