<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Sección 5 Modelos Estacionarios y Ajuste Lineal | Análisis de Series Temporales de Lluvia: Estación VENADO ORO VIVERO [21205580]</title>
  <meta name="description" content="Análisis de datos de precipitación diaria de la estación VENADO ORO VIVERO en Bogotá" />
  <meta name="generator" content="bookdown 0.37 and GitBook 2.6.7" />

  <meta property="og:title" content="Sección 5 Modelos Estacionarios y Ajuste Lineal | Análisis de Series Temporales de Lluvia: Estación VENADO ORO VIVERO [21205580]" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Análisis de datos de precipitación diaria de la estación VENADO ORO VIVERO en Bogotá" />
  <meta name="github-repo" content="seriestiempo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Sección 5 Modelos Estacionarios y Ajuste Lineal | Análisis de Series Temporales de Lluvia: Estación VENADO ORO VIVERO [21205580]" />
  
  <meta name="twitter:description" content="Análisis de datos de precipitación diaria de la estación VENADO ORO VIVERO en Bogotá" />
  

<meta name="author" content="Dónoban Rojas" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="holtwinters-suavizamiento.html"/>
<link rel="next" href="modelo-prophet-para-series-temporales.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/codefolding-lua-1.1/codefolding-lua.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.33/datatables.js"></script>
<link href="libs/dt-core-1.13.6/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.13.6/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.13.6/js/jquery.dataTables.min.js"></script>
<link href="libs/nouislider-7.0.10/jquery.nouislider.min.css" rel="stylesheet" />
<script src="libs/nouislider-7.0.10/jquery.nouislider.min.js"></script>
<link href="libs/selectize-0.12.0/selectize.bootstrap3.css" rel="stylesheet" />
<script src="libs/selectize-0.12.0/selectize.min.js"></script>
<link href="libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    background-color: #232629;
    color: #7a7c7d;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #7a7c7d;  padding-left: 4px; }
div.sourceCode
  { color: #cfcfc2; background-color: #232629; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span { color: #cfcfc2; } /* Normal */
code span.al { color: #95da4c; background-color: #4d1f24; font-weight: bold; } /* Alert */
code span.an { color: #3f8058; } /* Annotation */
code span.at { color: #2980b9; } /* Attribute */
code span.bn { color: #f67400; } /* BaseN */
code span.bu { color: #7f8c8d; } /* BuiltIn */
code span.cf { color: #fdbc4b; font-weight: bold; } /* ControlFlow */
code span.ch { color: #3daee9; } /* Char */
code span.cn { color: #27aeae; font-weight: bold; } /* Constant */
code span.co { color: #7a7c7d; } /* Comment */
code span.cv { color: #7f8c8d; } /* CommentVar */
code span.do { color: #a43340; } /* Documentation */
code span.dt { color: #2980b9; } /* DataType */
code span.dv { color: #f67400; } /* DecVal */
code span.er { color: #da4453; text-decoration: underline; } /* Error */
code span.ex { color: #0099ff; font-weight: bold; } /* Extension */
code span.fl { color: #f67400; } /* Float */
code span.fu { color: #8e44ad; } /* Function */
code span.im { color: #27ae60; } /* Import */
code span.in { color: #c45b00; } /* Information */
code span.kw { color: #cfcfc2; font-weight: bold; } /* Keyword */
code span.op { color: #cfcfc2; } /* Operator */
code span.ot { color: #27ae60; } /* Other */
code span.pp { color: #27ae60; } /* Preprocessor */
code span.re { color: #2980b9; background-color: #153042; } /* RegionMarker */
code span.sc { color: #3daee9; } /* SpecialChar */
code span.ss { color: #da4453; } /* SpecialString */
code span.st { color: #f44f4f; } /* String */
code span.va { color: #27aeae; } /* Variable */
code span.vs { color: #da4453; } /* VerbatimString */
code span.wa { color: #da4453; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Series Temporales de Lluvia</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Importancia del Análisis de la Precipitación</a></li>
<li class="chapter" data-level="2" data-path="analisisexploratorio.html"><a href="analisisexploratorio.html"><i class="fa fa-check"></i><b>2</b> Análisis Exploratorio</a>
<ul>
<li class="chapter" data-level="2.1" data-path="analisisexploratorio.html"><a href="analisisexploratorio.html#datos-faltantes"><i class="fa fa-check"></i><b>2.1</b> Datos Faltantes</a></li>
<li class="chapter" data-level="2.2" data-path="analisisexploratorio.html"><a href="analisisexploratorio.html#análisis-de-la-serie-temporal"><i class="fa fa-check"></i><b>2.2</b> Análisis de la Serie Temporal</a></li>
<li class="chapter" data-level="2.3" data-path="analisisexploratorio.html"><a href="analisisexploratorio.html#análisis-de-resultados"><i class="fa fa-check"></i><b>2.3</b> Análisis de Resultados</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="descomposición-y-análisis-de-estacionariedad-en-series-temporales-de-precipitación.html"><a href="descomposición-y-análisis-de-estacionariedad-en-series-temporales-de-precipitación.html"><i class="fa fa-check"></i><b>3</b> Descomposición y Análisis de Estacionariedad en Series Temporales de Precipitación</a>
<ul>
<li class="chapter" data-level="3.1" data-path="descomposición-y-análisis-de-estacionariedad-en-series-temporales-de-precipitación.html"><a href="descomposición-y-análisis-de-estacionariedad-en-series-temporales-de-precipitación.html#metodología"><i class="fa fa-check"></i><b>3.1</b> Metodología</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="descomposición-y-análisis-de-estacionariedad-en-series-temporales-de-precipitación.html"><a href="descomposición-y-análisis-de-estacionariedad-en-series-temporales-de-precipitación.html#evaluación-de-la-estacionariedad"><i class="fa fa-check"></i><b>3.1.1</b> Evaluación de la Estacionariedad:</a></li>
<li class="chapter" data-level="3.1.2" data-path="descomposición-y-análisis-de-estacionariedad-en-series-temporales-de-precipitación.html"><a href="descomposición-y-análisis-de-estacionariedad-en-series-temporales-de-precipitación.html#descomposición-de-la-serie-temporal"><i class="fa fa-check"></i><b>3.1.2</b> Descomposición de la Serie Temporal:</a></li>
<li class="chapter" data-level="3.1.3" data-path="descomposición-y-análisis-de-estacionariedad-en-series-temporales-de-precipitación.html"><a href="descomposición-y-análisis-de-estacionariedad-en-series-temporales-de-precipitación.html#transformación-logarítmica-y-análisis-de-diferenciación"><i class="fa fa-check"></i><b>3.1.3</b> Transformación Logarítmica y Análisis de Diferenciación:</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="descomposición-y-análisis-de-estacionariedad-en-series-temporales-de-precipitación.html"><a href="descomposición-y-análisis-de-estacionariedad-en-series-temporales-de-precipitación.html#análisis-de-resultados-1"><i class="fa fa-check"></i><b>3.2</b> Análisis de Resultados</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="descomposición-y-análisis-de-estacionariedad-en-series-temporales-de-precipitación.html"><a href="descomposición-y-análisis-de-estacionariedad-en-series-temporales-de-precipitación.html#análisis-de-estacionariedad"><i class="fa fa-check"></i><b>3.2.1</b> Análisis de Estacionariedad</a></li>
<li class="chapter" data-level="3.2.2" data-path="descomposición-y-análisis-de-estacionariedad-en-series-temporales-de-precipitación.html"><a href="descomposición-y-análisis-de-estacionariedad-en-series-temporales-de-precipitación.html#estructura-temporal"><i class="fa fa-check"></i><b>3.2.2</b> Estructura Temporal</a></li>
<li class="chapter" data-level="3.2.3" data-path="descomposición-y-análisis-de-estacionariedad-en-series-temporales-de-precipitación.html"><a href="descomposición-y-análisis-de-estacionariedad-en-series-temporales-de-precipitación.html#optimización-de-la-serie"><i class="fa fa-check"></i><b>3.2.3</b> Optimización de la Serie</a></li>
<li class="chapter" data-level="3.2.4" data-path="descomposición-y-análisis-de-estacionariedad-en-series-temporales-de-precipitación.html"><a href="descomposición-y-análisis-de-estacionariedad-en-series-temporales-de-precipitación.html#discusión-de-resultados"><i class="fa fa-check"></i><b>3.2.4</b> Discusión de Resultados</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="holtwinters-suavizamiento.html"><a href="holtwinters-suavizamiento.html"><i class="fa fa-check"></i><b>4</b> Métodos de Holt-Winters y Suavizamiento</a>
<ul>
<li class="chapter" data-level="4.1" data-path="holtwinters-suavizamiento.html"><a href="holtwinters-suavizamiento.html#metodologia"><i class="fa fa-check"></i><b>4.1</b> Metodologia</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="holtwinters-suavizamiento.html"><a href="holtwinters-suavizamiento.html#implementación-del-método-holt-winters-para-datos-mensuales"><i class="fa fa-check"></i><b>4.1.1</b> Implementación del método Holt-Winters para datos mensuales</a></li>
<li class="chapter" data-level="4.1.2" data-path="holtwinters-suavizamiento.html"><a href="holtwinters-suavizamiento.html#métodos-de-suavización-para-datos-diarios"><i class="fa fa-check"></i><b>4.1.2</b> Métodos de Suavización para Datos Diarios</a></li>
<li class="chapter" data-level="4.1.3" data-path="holtwinters-suavizamiento.html"><a href="holtwinters-suavizamiento.html#análisis-de-componentes-datos-mensuales"><i class="fa fa-check"></i><b>4.1.3</b> Análisis de Componentes (Datos Mensuales)</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="holtwinters-suavizamiento.html"><a href="holtwinters-suavizamiento.html#análisis-de-resultados-2"><i class="fa fa-check"></i><b>4.2</b> Análisis de Resultados</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="holtwinters-suavizamiento.html"><a href="holtwinters-suavizamiento.html#análisis-del-modelo-holt-winters"><i class="fa fa-check"></i><b>4.2.1</b> Análisis del Modelo Holt-Winters</a></li>
<li class="chapter" data-level="4.2.2" data-path="holtwinters-suavizamiento.html"><a href="holtwinters-suavizamiento.html#análisis-de-la-descomposición-temporal"><i class="fa fa-check"></i><b>4.2.2</b> Análisis de la Descomposición Temporal</a></li>
<li class="chapter" data-level="4.2.3" data-path="holtwinters-suavizamiento.html"><a href="holtwinters-suavizamiento.html#análisis-de-las-técnicas-de-suavización"><i class="fa fa-check"></i><b>4.2.3</b> Análisis de las Técnicas de Suavización</a></li>
<li class="chapter" data-level="4.2.4" data-path="holtwinters-suavizamiento.html"><a href="holtwinters-suavizamiento.html#pronósticos-y-tendencias"><i class="fa fa-check"></i><b>4.2.4</b> Pronósticos y Tendencias</a></li>
<li class="chapter" data-level="4.2.5" data-path="holtwinters-suavizamiento.html"><a href="holtwinters-suavizamiento.html#limitaciones-y-consideraciones"><i class="fa fa-check"></i><b>4.2.5</b> Limitaciones y Consideraciones</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="modelos-estacionarios.html"><a href="modelos-estacionarios.html"><i class="fa fa-check"></i><b>5</b> Modelos Estacionarios y Ajuste Lineal</a>
<ul>
<li class="chapter" data-level="5.1" data-path="modelos-estacionarios.html"><a href="modelos-estacionarios.html#metodología-1"><i class="fa fa-check"></i><b>5.1</b> Metodología</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="modelos-estacionarios.html"><a href="modelos-estacionarios.html#análisis-exploratorio-de-la-serie"><i class="fa fa-check"></i><b>5.1.1</b> Análisis Exploratorio de la Serie</a></li>
<li class="chapter" data-level="5.1.2" data-path="modelos-estacionarios.html"><a href="modelos-estacionarios.html#verificación-y-transformación-para-estacionariedad"><i class="fa fa-check"></i><b>5.1.2</b> Verificación y Transformación para Estacionariedad</a></li>
<li class="chapter" data-level="5.1.3" data-path="modelos-estacionarios.html"><a href="modelos-estacionarios.html#ajuste-del-modelo-arima"><i class="fa fa-check"></i><b>5.1.3</b> Ajuste del Modelo ARIMA</a></li>
<li class="chapter" data-level="5.1.4" data-path="modelos-estacionarios.html"><a href="modelos-estacionarios.html#validación-del-modelo"><i class="fa fa-check"></i><b>5.1.4</b> Validación del Modelo</a></li>
<li class="chapter" data-level="5.1.5" data-path="modelos-estacionarios.html"><a href="modelos-estacionarios.html#generación-de-pronósticos"><i class="fa fa-check"></i><b>5.1.5</b> Generación de Pronósticos</a></li>
<li class="chapter" data-level="5.1.6" data-path="modelos-estacionarios.html"><a href="modelos-estacionarios.html#evaluación-del-desempeño-del-modelo"><i class="fa fa-check"></i><b>5.1.6</b> Evaluación del Desempeño del Modelo</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="modelos-estacionarios.html"><a href="modelos-estacionarios.html#análisis-de-resultados-3"><i class="fa fa-check"></i><b>5.2</b> Análisis de Resultados</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="modelos-estacionarios.html"><a href="modelos-estacionarios.html#análisis-del-modelo-arima"><i class="fa fa-check"></i><b>5.2.1</b> Análisis del Modelo ARIMA</a></li>
<li class="chapter" data-level="5.2.2" data-path="modelos-estacionarios.html"><a href="modelos-estacionarios.html#diagnóstico-de-residuales"><i class="fa fa-check"></i><b>5.2.2</b> Diagnóstico de Residuales</a></li>
<li class="chapter" data-level="5.2.3" data-path="modelos-estacionarios.html"><a href="modelos-estacionarios.html#evaluación-del-desempeño"><i class="fa fa-check"></i><b>5.2.3</b> Evaluación del Desempeño</a></li>
<li class="chapter" data-level="5.2.4" data-path="modelos-estacionarios.html"><a href="modelos-estacionarios.html#pronósticos"><i class="fa fa-check"></i><b>5.2.4</b> Pronósticos</a></li>
<li class="chapter" data-level="5.2.5" data-path="modelos-estacionarios.html"><a href="modelos-estacionarios.html#fortalezas-y-limitaciones-del-modelo"><i class="fa fa-check"></i><b>5.2.5</b> Fortalezas y Limitaciones del Modelo</a></li>
<li class="chapter" data-level="5.2.6" data-path="modelos-estacionarios.html"><a href="modelos-estacionarios.html#conclusiones"><i class="fa fa-check"></i><b>5.2.6</b> Conclusiones</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="modelo-prophet-para-series-temporales.html"><a href="modelo-prophet-para-series-temporales.html"><i class="fa fa-check"></i><b>6</b> Modelo Prophet para Series Temporales</a>
<ul>
<li class="chapter" data-level="6.1" data-path="modelo-prophet-para-series-temporales.html"><a href="modelo-prophet-para-series-temporales.html#metodología-2"><i class="fa fa-check"></i><b>6.1</b> Metodología</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="modelo-prophet-para-series-temporales.html"><a href="modelo-prophet-para-series-temporales.html#implementación-del-modelo-prophet"><i class="fa fa-check"></i><b>6.1.1</b> Implementación del Modelo Prophet</a></li>
<li class="chapter" data-level="6.1.2" data-path="modelo-prophet-para-series-temporales.html"><a href="modelo-prophet-para-series-temporales.html#análisis-de-componentes-y-visualización"><i class="fa fa-check"></i><b>6.1.2</b> Análisis de Componentes y Visualización</a></li>
<li class="chapter" data-level="6.1.3" data-path="modelo-prophet-para-series-temporales.html"><a href="modelo-prophet-para-series-temporales.html#evaluación-del-desempeño-y-diagnóstico"><i class="fa fa-check"></i><b>6.1.3</b> Evaluación del Desempeño y Diagnóstico</a></li>
<li class="chapter" data-level="6.1.4" data-path="modelo-prophet-para-series-temporales.html"><a href="modelo-prophet-para-series-temporales.html#comparación-con-modelo-arima"><i class="fa fa-check"></i><b>6.1.4</b> Comparación con Modelo ARIMA</a></li>
<li class="chapter" data-level="6.1.5" data-path="modelo-prophet-para-series-temporales.html"><a href="modelo-prophet-para-series-temporales.html#justificación-del-enfoque-de-regresión"><i class="fa fa-check"></i><b>6.1.5</b> Justificación del Enfoque de Regresión</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="modelo-prophet-para-series-temporales.html"><a href="modelo-prophet-para-series-temporales.html#análisis-de-resultados-4"><i class="fa fa-check"></i><b>6.2</b> Análisis de Resultados</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Análisis de Series Temporales de Lluvia: Estación VENADO ORO VIVERO [21205580]</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="modelos-estacionarios" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">Sección 5</span> Modelos Estacionarios y Ajuste Lineal<a href="modelos-estacionarios.html#modelos-estacionarios" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Este análisis complementa el trabajo previo sobre los métodos de Holt-Winters mediante la exploración de modelos estacionarios y ajustes lineales de la serie temporal. El objetivo es identificar y modelar los componentes fundamentales de la serie, asegurando su estacionariedad para realizar pronósticos más precisos.</p>
<div id="metodología-1" class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> Metodología<a href="modelos-estacionarios.html#metodología-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Para el análisis de estacionariedad y ajuste de modelos lineales, se realizó el siguiente proceso:</p>
<ol style="list-style-type: decimal">
<li>Análisis exploratorio de la serie temporal</li>
<li>Verificación de estacionariedad</li>
<li>Transformaciones necesarias para lograr estacionariedad</li>
<li>Ajuste de modelos ARIMA (Autoregressive Integrated Moving Average)</li>
<li>Validación de residuales</li>
<li>Generación de pronósticos</li>
</ol>
<div id="análisis-exploratorio-de-la-serie" class="section level3 hasAnchor" number="5.1.1">
<h3><span class="header-section-number">5.1.1</span> Análisis Exploratorio de la Serie<a href="modelos-estacionarios.html#análisis-exploratorio-de-la-serie" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>El análisis inicial de la serie temporal revela sus características fundamentales y patrones de comportamiento:</p>
<details class=chunk-details><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="modelos-estacionarios.html#cb31-1" tabindex="-1"></a><span class="co"># Visualización inicial de la serie</span></span>
<span id="cb31-2"><a href="modelos-estacionarios.html#cb31-2" tabindex="-1"></a><span class="fu">plot</span>(ts_lluvia, <span class="at">main =</span> <span class="st">&quot;Serie Original de Precipitación&quot;</span>,</span>
<span id="cb31-3"><a href="modelos-estacionarios.html#cb31-3" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Tiempo&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Precipitación (mm)&quot;</span>,</span>
<span id="cb31-4"><a href="modelos-estacionarios.html#cb31-4" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">&quot;darkblue&quot;</span>)</span></code></pre></div>
</details>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<p>La serie muestra una alta variabilidad con valores que oscilan principalmente entre 0 y 40 mm de precipitación diaria, con algunos valores extremos que alcanzan los 60 mm. Se observa una ligera tendencia descendente a lo largo del período, particularmente visible después de 2015.</p>
<details class=chunk-details><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="modelos-estacionarios.html#cb32-1" tabindex="-1"></a><span class="co"># Análisis de ciclo estacional mensual</span></span>
<span id="cb32-2"><a href="modelos-estacionarios.html#cb32-2" tabindex="-1"></a><span class="fu">boxplot</span>(ts_mensual <span class="sc">~</span> <span class="fu">cycle</span>(ts_mensual), </span>
<span id="cb32-3"><a href="modelos-estacionarios.html#cb32-3" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">&quot;Patrón Estacional de Precipitación&quot;</span>,</span>
<span id="cb32-4"><a href="modelos-estacionarios.html#cb32-4" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">&quot;Mes&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Precipitación (mm)&quot;</span>)</span></code></pre></div>
</details>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
<p>La estacionalidad de las precipitaciones se evidencia claramente en el gráfico, donde se observan patrones distintivos a lo largo del año. Los meses 4 (abril) y 11 (noviembre) presentan las mayores medianas de precipitación y mayor dispersión, como se observa en el tamaño de las cajas. Los meses de julio a septiembre (7-9) muestran una notable disminución en las precipitaciones, con cajas más pequeñas y medianas más bajas, indicando un período más seco y con menor variabilidad. Se observan algunos valores atípicos (outliers) especialmente en los meses 7 y 10, representados por puntos individuales, que indican eventos de lluvia inusualmente intensos para esos meses. La transición entre estaciones húmedas y secas no es abrupta, sino que muestra cambios graduales, con meses intermedios como mayo (5) y octubre (10) que presentan niveles moderados de precipitación.</p>
</div>
<div id="verificación-y-transformación-para-estacionariedad" class="section level3 hasAnchor" number="5.1.2">
<h3><span class="header-section-number">5.1.2</span> Verificación y Transformación para Estacionariedad<a href="modelos-estacionarios.html#verificación-y-transformación-para-estacionariedad" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Para asegurar la estacionariedad, necesaria para el modelado ARIMA, se aplicarón pruebas formales y transformaciones:</p>
<details class=chunk-details><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="modelos-estacionarios.html#cb33-1" tabindex="-1"></a><span class="co"># Test de Dickey-Fuller Aumentado</span></span>
<span id="cb33-2"><a href="modelos-estacionarios.html#cb33-2" tabindex="-1"></a><span class="fu">adf.test</span>(ts_lluvia)</span></code></pre></div>
</details>
<pre><code>## Augmented Dickey-Fuller Test 
## alternative: stationary 
##  
## Type 1: no drift no trend 
##       lag   ADF p.value
##  [1,]   0 -46.0    0.01
##  [2,]   1 -32.7    0.01
##  [3,]   2 -26.3    0.01
##  [4,]   3 -21.6    0.01
##  [5,]   4 -19.0    0.01
##  [6,]   5 -17.2    0.01
##  [7,]   6 -15.8    0.01
##  [8,]   7 -14.7    0.01
##  [9,]   8 -13.8    0.01
## [10,]   9 -12.8    0.01
## Type 2: with drift no trend 
##       lag   ADF p.value
##  [1,]   0 -54.4    0.01
##  [2,]   1 -40.4    0.01
##  [3,]   2 -33.6    0.01
##  [4,]   3 -28.4    0.01
##  [5,]   4 -25.6    0.01
##  [6,]   5 -23.8    0.01
##  [7,]   6 -22.2    0.01
##  [8,]   7 -21.1    0.01
##  [9,]   8 -20.2    0.01
## [10,]   9 -19.1    0.01
## Type 3: with drift and trend 
##       lag   ADF p.value
##  [1,]   0 -54.4    0.01
##  [2,]   1 -40.4    0.01
##  [3,]   2 -33.7    0.01
##  [4,]   3 -28.4    0.01
##  [5,]   4 -25.7    0.01
##  [6,]   5 -23.8    0.01
##  [7,]   6 -22.3    0.01
##  [8,]   7 -21.1    0.01
##  [9,]   8 -20.3    0.01
## [10,]   9 -19.1    0.01
## ---- 
## Note: in fact, p.value = 0.01 means p.value &lt;= 0.01</code></pre>
<details class=chunk-details><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="modelos-estacionarios.html#cb35-1" tabindex="-1"></a><span class="co"># Transformación logarítmica y diferenciación</span></span>
<span id="cb35-2"><a href="modelos-estacionarios.html#cb35-2" tabindex="-1"></a>log_lluvia <span class="ot">&lt;-</span> <span class="fu">log</span>(ts_lluvia <span class="sc">+</span> <span class="dv">1</span>)  <span class="co"># +1 para manejar valores cero</span></span>
<span id="cb35-3"><a href="modelos-estacionarios.html#cb35-3" tabindex="-1"></a>diff_log_lluvia <span class="ot">&lt;-</span> <span class="fu">diff</span>(log_lluvia)</span>
<span id="cb35-4"><a href="modelos-estacionarios.html#cb35-4" tabindex="-1"></a></span>
<span id="cb35-5"><a href="modelos-estacionarios.html#cb35-5" tabindex="-1"></a><span class="co"># Verificar estacionariedad después de transformación</span></span>
<span id="cb35-6"><a href="modelos-estacionarios.html#cb35-6" tabindex="-1"></a><span class="fu">adf.test</span>(diff_log_lluvia)</span></code></pre></div>
</details>
<pre><code>## Augmented Dickey-Fuller Test 
## alternative: stationary 
##  
## Type 1: no drift no trend 
##       lag    ADF p.value
##  [1,]   0 -107.6    0.01
##  [2,]   1  -78.3    0.01
##  [3,]   2  -66.0    0.01
##  [4,]   3  -57.1    0.01
##  [5,]   4  -50.4    0.01
##  [6,]   5  -45.6    0.01
##  [7,]   6  -42.0    0.01
##  [8,]   7  -39.2    0.01
##  [9,]   8  -37.0    0.01
## [10,]   9  -35.3    0.01
## Type 2: with drift no trend 
##       lag    ADF p.value
##  [1,]   0 -107.5    0.01
##  [2,]   1  -78.3    0.01
##  [3,]   2  -66.0    0.01
##  [4,]   3  -57.1    0.01
##  [5,]   4  -50.4    0.01
##  [6,]   5  -45.6    0.01
##  [7,]   6  -42.0    0.01
##  [8,]   7  -39.2    0.01
##  [9,]   8  -37.0    0.01
## [10,]   9  -35.3    0.01
## Type 3: with drift and trend 
##       lag    ADF p.value
##  [1,]   0 -107.5    0.01
##  [2,]   1  -78.3    0.01
##  [3,]   2  -66.0    0.01
##  [4,]   3  -57.1    0.01
##  [5,]   4  -50.4    0.01
##  [6,]   5  -45.6    0.01
##  [7,]   6  -42.0    0.01
##  [8,]   7  -39.2    0.01
##  [9,]   8  -37.0    0.01
## [10,]   9  -35.3    0.01
## ---- 
## Note: in fact, p.value = 0.01 means p.value &lt;= 0.01</code></pre>
<p>El análisis de estacionariedad mediante la prueba de Dickey-Fuller Aumentada (ADF) revela resultados significativos:</p>
<ol style="list-style-type: decimal">
<li>Serie Original:</li>
</ol>
<ul>
<li>Los valores del estadístico ADF son altamente significativos (p ≤ 0.01) para todos los rezagos analizados</li>
<li>Los tres tipos de prueba (sin deriva ni tendencia, con deriva, con deriva y tendencia) muestran resultados consistentes</li>
<li>Los valores ADF varían desde -54.4 hasta -12.8, todos indicando un fuerte rechazo de la hipótesis nula de no estacionariedad</li>
</ul>
<ol start="2" style="list-style-type: decimal">
<li>Serie Diferenciada:</li>
</ol>
<ul>
<li>La serie diferenciada muestra estadísticos ADF aún más extremos, con valores desde -107.6 hasta -35.3</li>
<li>Mantiene la significancia estadística (p ≤ 0.01) en todos los casos</li>
<li>Los resultados son robustos a través de los diferentes tipos de prueba y rezagos</li>
</ul>
</div>
<div id="ajuste-del-modelo-arima" class="section level3 hasAnchor" number="5.1.3">
<h3><span class="header-section-number">5.1.3</span> Ajuste del Modelo ARIMA<a href="modelos-estacionarios.html#ajuste-del-modelo-arima" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Una vez confirmada la estacionariedad de la serie original, se procedió con el ajuste del modelo ARIMA:</p>
<details class=chunk-details><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="modelos-estacionarios.html#cb37-1" tabindex="-1"></a><span class="co"># Ajuste automático del modelo ARIMA</span></span>
<span id="cb37-2"><a href="modelos-estacionarios.html#cb37-2" tabindex="-1"></a>modelo_arima <span class="ot">&lt;-</span> <span class="fu">auto.arima</span>(ts_lluvia)</span>
<span id="cb37-3"><a href="modelos-estacionarios.html#cb37-3" tabindex="-1"></a></span>
<span id="cb37-4"><a href="modelos-estacionarios.html#cb37-4" tabindex="-1"></a><span class="co"># Resumen del modelo</span></span>
<span id="cb37-5"><a href="modelos-estacionarios.html#cb37-5" tabindex="-1"></a><span class="fu">summary</span>(modelo_arima)</span></code></pre></div>
</details>
<pre><code>## Series: ts_lluvia 
## ARIMA(4,0,1) with non-zero mean 
## 
## Coefficients:
##          ar1      ar2      ar3     ar4      ma1    mean
##       0.8246  -0.0887  -0.0054  0.0414  -0.5681  3.4678
## s.e.  0.1349   0.0391   0.0189  0.0198   0.1348  0.1672
## 
## sigma^2 = 41.99:  log likelihood = -17671.5
## AIC=35357.01   AICc=35357.03   BIC=35403.14
## 
## Training set error measures:
##                        ME    RMSE     MAE  MPE MAPE      MASE         ACF1
## Training set 1.697681e-05 6.47636 3.82685 -Inf  Inf 0.7483815 0.0004084742</code></pre>
</div>
<div id="validación-del-modelo" class="section level3 hasAnchor" number="5.1.4">
<h3><span class="header-section-number">5.1.4</span> Validación del Modelo<a href="modelos-estacionarios.html#validación-del-modelo" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Se realizó un análisis completo de los residuales para verificar los supuestos del modelo:</p>
<details class=chunk-details><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="modelos-estacionarios.html#cb39-1" tabindex="-1"></a><span class="co"># Análisis de residuales</span></span>
<span id="cb39-2"><a href="modelos-estacionarios.html#cb39-2" tabindex="-1"></a>residuales <span class="ot">&lt;-</span> <span class="fu">residuals</span>(modelo_arima)</span>
<span id="cb39-3"><a href="modelos-estacionarios.html#cb39-3" tabindex="-1"></a></span>
<span id="cb39-4"><a href="modelos-estacionarios.html#cb39-4" tabindex="-1"></a><span class="co"># Gráficos diagnósticos</span></span>
<span id="cb39-5"><a href="modelos-estacionarios.html#cb39-5" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb39-6"><a href="modelos-estacionarios.html#cb39-6" tabindex="-1"></a></span>
<span id="cb39-7"><a href="modelos-estacionarios.html#cb39-7" tabindex="-1"></a><span class="co"># 1. Gráfico de residuales vs tiempo</span></span>
<span id="cb39-8"><a href="modelos-estacionarios.html#cb39-8" tabindex="-1"></a><span class="fu">plot</span>(residuales, <span class="at">type=</span><span class="st">&#39;l&#39;</span>, </span>
<span id="cb39-9"><a href="modelos-estacionarios.html#cb39-9" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&#39;Residuales vs Tiempo&#39;</span>,</span>
<span id="cb39-10"><a href="modelos-estacionarios.html#cb39-10" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">&#39;Residuales&#39;</span>, <span class="at">xlab=</span><span class="st">&#39;Tiempo&#39;</span>)</span>
<span id="cb39-11"><a href="modelos-estacionarios.html#cb39-11" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>, <span class="at">col=</span><span class="st">&#39;red&#39;</span>)</span>
<span id="cb39-12"><a href="modelos-estacionarios.html#cb39-12" tabindex="-1"></a></span>
<span id="cb39-13"><a href="modelos-estacionarios.html#cb39-13" tabindex="-1"></a><span class="co"># 2. Gráfico Q-Q para normalidad</span></span>
<span id="cb39-14"><a href="modelos-estacionarios.html#cb39-14" tabindex="-1"></a><span class="fu">qqnorm</span>(residuales)</span>
<span id="cb39-15"><a href="modelos-estacionarios.html#cb39-15" tabindex="-1"></a><span class="fu">qqline</span>(residuales)</span>
<span id="cb39-16"><a href="modelos-estacionarios.html#cb39-16" tabindex="-1"></a></span>
<span id="cb39-17"><a href="modelos-estacionarios.html#cb39-17" tabindex="-1"></a><span class="co"># 3. ACF de residuales</span></span>
<span id="cb39-18"><a href="modelos-estacionarios.html#cb39-18" tabindex="-1"></a><span class="fu">acf</span>(residuales, <span class="at">main=</span><span class="st">&#39;ACF de Residuales&#39;</span>)</span>
<span id="cb39-19"><a href="modelos-estacionarios.html#cb39-19" tabindex="-1"></a></span>
<span id="cb39-20"><a href="modelos-estacionarios.html#cb39-20" tabindex="-1"></a><span class="co"># 4. PACF de residuales</span></span>
<span id="cb39-21"><a href="modelos-estacionarios.html#cb39-21" tabindex="-1"></a><span class="fu">pacf</span>(residuales, <span class="at">main=</span><span class="st">&#39;PACF de Residuales&#39;</span>)</span></code></pre></div>
</details>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<details class=chunk-details><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="modelos-estacionarios.html#cb40-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb40-2"><a href="modelos-estacionarios.html#cb40-2" tabindex="-1"></a></span>
<span id="cb40-3"><a href="modelos-estacionarios.html#cb40-3" tabindex="-1"></a><span class="co"># Tests formales</span></span>
<span id="cb40-4"><a href="modelos-estacionarios.html#cb40-4" tabindex="-1"></a><span class="co"># Test de normalidad con una muestra aleatoria de 5000 observaciones</span></span>
<span id="cb40-5"><a href="modelos-estacionarios.html#cb40-5" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>) <span class="co"># Para reproducibilidad</span></span>
<span id="cb40-6"><a href="modelos-estacionarios.html#cb40-6" tabindex="-1"></a>muestra_residuales <span class="ot">&lt;-</span> <span class="fu">sample</span>(residuales, <span class="fu">min</span>(<span class="dv">5000</span>, <span class="fu">length</span>(residuales)))</span>
<span id="cb40-7"><a href="modelos-estacionarios.html#cb40-7" tabindex="-1"></a>shapiro_test <span class="ot">&lt;-</span> <span class="fu">shapiro.test</span>(muestra_residuales)</span>
<span id="cb40-8"><a href="modelos-estacionarios.html#cb40-8" tabindex="-1"></a><span class="fu">print</span>(<span class="st">&quot;Test de Shapiro-Wilk para normalidad (muestra aleatoria):&quot;</span>)</span></code></pre></div>
</details>
<pre><code>## [1] &quot;Test de Shapiro-Wilk para normalidad (muestra aleatoria):&quot;</code></pre>
<details class=chunk-details><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="modelos-estacionarios.html#cb42-1" tabindex="-1"></a><span class="fu">print</span>(shapiro_test)</span></code></pre></div>
</details>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  muestra_residuales
## W = 0.6502, p-value &lt; 2.2e-16</code></pre>
<details class=chunk-details><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="modelos-estacionarios.html#cb44-1" tabindex="-1"></a><span class="co"># Test de independencia</span></span>
<span id="cb44-2"><a href="modelos-estacionarios.html#cb44-2" tabindex="-1"></a>box_test <span class="ot">&lt;-</span> <span class="fu">Box.test</span>(residuales, <span class="at">type =</span> <span class="st">&quot;Ljung-Box&quot;</span>, <span class="at">lag =</span> <span class="dv">20</span>)</span>
<span id="cb44-3"><a href="modelos-estacionarios.html#cb44-3" tabindex="-1"></a><span class="fu">print</span>(<span class="st">&quot;Test de Ljung-Box para independencia:&quot;</span>)</span></code></pre></div>
</details>
<pre><code>## [1] &quot;Test de Ljung-Box para independencia:&quot;</code></pre>
<details class=chunk-details><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="modelos-estacionarios.html#cb46-1" tabindex="-1"></a><span class="fu">print</span>(box_test)</span></code></pre></div>
</details>
<pre><code>## 
##  Box-Ljung test
## 
## data:  residuales
## X-squared = 11.604, df = 20, p-value = 0.929</code></pre>
</div>
<div id="generación-de-pronósticos" class="section level3 hasAnchor" number="5.1.5">
<h3><span class="header-section-number">5.1.5</span> Generación de Pronósticos<a href="modelos-estacionarios.html#generación-de-pronósticos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Se generan y visualizan los pronósticos para los próximos períodos:</p>
<details class=chunk-details><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="modelos-estacionarios.html#cb48-1" tabindex="-1"></a>pronostico <span class="ot">&lt;-</span> forecast<span class="sc">::</span><span class="fu">forecast</span>(modelo_arima, <span class="at">h =</span> <span class="dv">30</span>)</span>
<span id="cb48-2"><a href="modelos-estacionarios.html#cb48-2" tabindex="-1"></a></span>
<span id="cb48-3"><a href="modelos-estacionarios.html#cb48-3" tabindex="-1"></a><span class="co"># Visualización de pronósticos</span></span>
<span id="cb48-4"><a href="modelos-estacionarios.html#cb48-4" tabindex="-1"></a><span class="fu">plot</span>(pronostico, </span>
<span id="cb48-5"><a href="modelos-estacionarios.html#cb48-5" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Pronóstico de Precipitación&quot;</span>,</span>
<span id="cb48-6"><a href="modelos-estacionarios.html#cb48-6" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Tiempo&quot;</span>, </span>
<span id="cb48-7"><a href="modelos-estacionarios.html#cb48-7" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Precipitación (mm)&quot;</span>,</span>
<span id="cb48-8"><a href="modelos-estacionarios.html#cb48-8" tabindex="-1"></a>     <span class="at">fcol =</span> <span class="st">&quot;red&quot;</span>, </span>
<span id="cb48-9"><a href="modelos-estacionarios.html#cb48-9" tabindex="-1"></a>     <span class="at">shadecols =</span> <span class="fu">c</span>(<span class="st">&quot;gray80&quot;</span>, <span class="st">&quot;gray90&quot;</span>))</span>
<span id="cb48-10"><a href="modelos-estacionarios.html#cb48-10" tabindex="-1"></a><span class="fu">grid</span>()</span></code></pre></div>
</details>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
<details class=chunk-details><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="modelos-estacionarios.html#cb49-1" tabindex="-1"></a><span class="co"># Tabla con valores pronosticados</span></span>
<span id="cb49-2"><a href="modelos-estacionarios.html#cb49-2" tabindex="-1"></a><span class="fu">print</span>(pronostico)</span></code></pre></div>
</details>
<pre><code>##           Point Forecast     Lo 80    Hi 80     Lo 95    Hi 95
## 2022.6192       3.209337 -5.095087 11.51376 -9.491184 15.90986
## 2022.6219       3.353036 -5.220187 11.92626 -9.758577 16.46465
## 2022.6247       3.866086 -4.767571 12.49974 -9.337954 17.07013
## 2022.6274       3.705678 -4.949289 12.36065 -9.530953 16.94231
## 2022.6301       3.618556 -5.068181 12.30529 -9.666662 16.90377
## 2022.6329       3.564108 -5.146237 12.27445 -9.757215 16.88543
## 2022.6356       3.549042 -5.175731 12.27382 -9.794347 16.89243
## 2022.6384       3.535281 -5.197670 12.26823 -9.820616 16.89118
## 2022.6411       3.521959 -5.215952 12.25987 -9.841522 16.88544
## 2022.6438       3.510021 -5.230995 12.25104 -9.858210 16.87825
## 2022.6466       3.500810 -5.242159 12.24378 -9.870407 16.87203
## 2022.6493       3.493776 -5.250407 12.23796 -9.879298 16.86685
## 2022.6521       3.488306 -5.256630 12.23324 -9.885919 16.86253
## 2022.6548       3.483975 -5.261427 12.22938 -9.890963 16.85891
## 2022.6575       3.480545 -5.265146 12.22624 -9.894835 16.85593
## 2022.6603       3.477840 -5.268031 12.22371 -9.897815 16.85350
## 2022.6630       3.475711 -5.270272 12.22169 -9.900115 16.85154
## 2022.6658       3.474034 -5.272018 12.22009 -9.901898 16.84997
## 2022.6685       3.472713 -5.273382 12.21881 -9.903285 16.84871
## 2022.6712       3.471671 -5.274450 12.21779 -9.904367 16.84771
## 2022.6740       3.470851 -5.275287 12.21699 -9.905213 16.84691
## 2022.6767       3.470205 -5.275944 12.21635 -9.905875 16.84628
## 2022.6795       3.469695 -5.276459 12.21585 -9.906394 16.84578
## 2022.6822       3.469294 -5.276865 12.21545 -9.906801 16.84539
## 2022.6849       3.468978 -5.277183 12.21514 -9.907121 16.84508
## 2022.6877       3.468729 -5.277434 12.21489 -9.907373 16.84483
## 2022.6904       3.468532 -5.277631 12.21470 -9.907571 16.84464
## 2022.6932       3.468378 -5.277787 12.21454 -9.907726 16.84448
## 2022.6959       3.468256 -5.277909 12.21442 -9.907849 16.84436
## 2022.6986       3.468160 -5.278005 12.21432 -9.907945 16.84426</code></pre>
</div>
<div id="evaluación-del-desempeño-del-modelo" class="section level3 hasAnchor" number="5.1.6">
<h3><span class="header-section-number">5.1.6</span> Evaluación del Desempeño del Modelo<a href="modelos-estacionarios.html#evaluación-del-desempeño-del-modelo" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Se calculan las métricas de precisión del modelo:</p>
<details class=chunk-details><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="modelos-estacionarios.html#cb51-1" tabindex="-1"></a><span class="co"># Métricas de precisión</span></span>
<span id="cb51-2"><a href="modelos-estacionarios.html#cb51-2" tabindex="-1"></a><span class="fu">accuracy</span>(modelo_arima)</span></code></pre></div>
</details>
<pre><code>##                        ME    RMSE     MAE  MPE MAPE      MASE         ACF1
## Training set 1.697681e-05 6.47636 3.82685 -Inf  Inf 0.7483815 0.0004084742</code></pre>
<details class=chunk-details><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="modelos-estacionarios.html#cb53-1" tabindex="-1"></a><span class="co"># Comparación con datos reales (últimos 30 días)</span></span>
<span id="cb53-2"><a href="modelos-estacionarios.html#cb53-2" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(ts_lluvia)</span>
<span id="cb53-3"><a href="modelos-estacionarios.html#cb53-3" tabindex="-1"></a>train <span class="ot">&lt;-</span> <span class="fu">subset</span>(ts_lluvia, <span class="at">end =</span> n<span class="dv">-30</span>)</span>
<span id="cb53-4"><a href="modelos-estacionarios.html#cb53-4" tabindex="-1"></a>test <span class="ot">&lt;-</span> <span class="fu">subset</span>(ts_lluvia, <span class="at">start =</span> n<span class="dv">-29</span>)</span>
<span id="cb53-5"><a href="modelos-estacionarios.html#cb53-5" tabindex="-1"></a></span>
<span id="cb53-6"><a href="modelos-estacionarios.html#cb53-6" tabindex="-1"></a><span class="co"># Ajuste del modelo en datos de entrenamiento</span></span>
<span id="cb53-7"><a href="modelos-estacionarios.html#cb53-7" tabindex="-1"></a>modelo_test <span class="ot">&lt;-</span> <span class="fu">auto.arima</span>(train)</span>
<span id="cb53-8"><a href="modelos-estacionarios.html#cb53-8" tabindex="-1"></a>forecast_test <span class="ot">&lt;-</span> forecast<span class="sc">::</span><span class="fu">forecast</span>(modelo_test, <span class="at">h =</span> <span class="dv">30</span>)</span>
<span id="cb53-9"><a href="modelos-estacionarios.html#cb53-9" tabindex="-1"></a></span>
<span id="cb53-10"><a href="modelos-estacionarios.html#cb53-10" tabindex="-1"></a><span class="co"># Error de predicción</span></span>
<span id="cb53-11"><a href="modelos-estacionarios.html#cb53-11" tabindex="-1"></a>error_pred <span class="ot">&lt;-</span> test <span class="sc">-</span> forecast_test<span class="sc">$</span>mean</span>
<span id="cb53-12"><a href="modelos-estacionarios.html#cb53-12" tabindex="-1"></a><span class="fu">print</span>(<span class="st">&quot;Error Medio Absoluto de Predicción:&quot;</span>)</span></code></pre></div>
</details>
<pre><code>## [1] &quot;Error Medio Absoluto de Predicción:&quot;</code></pre>
<details class=chunk-details><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="modelos-estacionarios.html#cb55-1" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">mean</span>(<span class="fu">abs</span>(error_pred)))</span></code></pre></div>
</details>
<pre><code>## [1] 3.338078</code></pre>
</div>
</div>
<div id="análisis-de-resultados-3" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> Análisis de Resultados<a href="modelos-estacionarios.html#análisis-de-resultados-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="análisis-del-modelo-arima" class="section level3 hasAnchor" number="5.2.1">
<h3><span class="header-section-number">5.2.1</span> Análisis del Modelo ARIMA<a href="modelos-estacionarios.html#análisis-del-modelo-arima" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>El modelo seleccionado automáticamente es un ARIMA(4,0,1) con media no nula, lo cual indica:</p>
<ul>
<li>Un componente autorregresivo de orden 4 (AR(4))</li>
<li>Ninguna diferenciación necesaria (confirma la estacionariedad inicial)</li>
<li>Un componente de media móvil de orden 1 (MA(1))</li>
</ul>
<p>Los coeficientes más significativos son:</p>
<ul>
<li>AR1 (0.8246): fuerte dependencia del valor inmediatamente anterior</li>
<li>MA1 (-0.5681): corrección moderada de errores previos</li>
<li>Media (3.4678 mm): nivel medio de precipitación diaria</li>
</ul>
</div>
<div id="diagnóstico-de-residuales" class="section level3 hasAnchor" number="5.2.2">
<h3><span class="header-section-number">5.2.2</span> Diagnóstico de Residuales<a href="modelos-estacionarios.html#diagnóstico-de-residuales" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Análisis Visual:</p>
<ul>
<li>Los residuales vs tiempo muestran una varianza relativamente constante alrededor de cero</li>
<li>El gráfico Q-Q muestra desviaciones de la normalidad, especialmente en las colas</li>
<li>Las funciones ACF y PACF muestran correlaciones dentro de las bandas de confianza</li>
</ul>
<p>Tests Formales:</p>
<ul>
<li>Test de Shapiro-Wilk: p-valor &lt; 2.2e-16 indica no normalidad de los residuales</li>
<li>Test de Ljung-Box: p-valor = 0.929 sugiere independencia de los residuales</li>
</ul>
</div>
<div id="evaluación-del-desempeño" class="section level3 hasAnchor" number="5.2.3">
<h3><span class="header-section-number">5.2.3</span> Evaluación del Desempeño<a href="modelos-estacionarios.html#evaluación-del-desempeño" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Las métricas de error muestran:</p>
<ul>
<li>Error Medio (ME) cercano a cero (1.70e-05): ausencia de sesgo sistemático</li>
<li>RMSE de 6.48 mm: error cuadrático medio moderado</li>
<li>MAE de 3.83 mm: error absoluto medio aceptable</li>
<li>Error Medio Absoluto de Predicción: 3.34 mm, ligeramente mejor que el MAE del conjunto de entrenamiento</li>
</ul>
</div>
<div id="pronósticos" class="section level3 hasAnchor" number="5.2.4">
<h3><span class="header-section-number">5.2.4</span> Pronósticos<a href="modelos-estacionarios.html#pronósticos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Los pronósticos generados muestran:</p>
<ul>
<li>Valores puntuales cercanos a la media histórica (≈3.5 mm)</li>
<li>Intervalos de predicción amplios, reflejando la alta variabilidad inherente</li>
<li>Bandas de confianza del 80% y 95% que capturan adecuadamente la variabilidad histórica</li>
</ul>
</div>
<div id="fortalezas-y-limitaciones-del-modelo" class="section level3 hasAnchor" number="5.2.5">
<h3><span class="header-section-number">5.2.5</span> Fortalezas y Limitaciones del Modelo<a href="modelos-estacionarios.html#fortalezas-y-limitaciones-del-modelo" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Fortalezas:</p>
<ul>
<li>Captura adecuadamente la estructura de autocorrelación</li>
<li>Residuales independientes (según Ljung-Box)</li>
<li>Error de predicción razonable para datos de precipitación diaria</li>
</ul>
<p>Limitaciones:</p>
<ul>
<li>No normalidad de residuales</li>
<li>MAPE indefinido debido a valores cero en la serie</li>
<li>Intervalos de predicción amplios</li>
</ul>
</div>
<div id="conclusiones" class="section level3 hasAnchor" number="5.2.6">
<h3><span class="header-section-number">5.2.6</span> Conclusiones<a href="modelos-estacionarios.html#conclusiones" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>El modelo ARIMA(4,0,1) proporciona un ajuste aceptable para datos de precipitación diaria, con errores de predicción razonables considerando la alta variabilidad inherente a este tipo de datos. Aunque no cumple el supuesto de normalidad, la independencia de los residuales y la precisión de las predicciones sugieren que es útil para propósitos prácticos de pronóstico a corto plazo.</p>
<p>Las predicciones deben interpretarse con cautela, considerando:</p>
<ol style="list-style-type: decimal">
<li>La amplitud de los intervalos de confianza</li>
<li>La naturaleza variable de la precipitación</li>
<li>La tendencia del modelo a regresar hacia la media</li>
</ol>
<p>Este análisis proporciona una base sólida para la comprensión y predicción del comportamiento de la precipitación diaria, aunque se recomienda complementar con otros indicadores meteorológicos para decisiones críticas.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="holtwinters-suavizamiento.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="modelo-prophet-para-series-temporales.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "night",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
